### ISSUE TITLE
Set up string extraction & Transifex integration

### ISSUE THREAD

**Issue by gunchleoc** [widelands/wl_addons_server#1]
Transifex project is at https://www.transifex.com/widelands/widelands-addons/

**Comment by Noordfrees** [comment]
I'm experimenting with Transifex's GitHub integration now. I've set up integration for the 14 add-ons currently present on the server. TX automatically pushes PO files to the `transifex` branch now and gets its POT files from there as well. A GitHub action nightly merges any changes from the `transifex` branch into master, runs the `buildcats.sh` script, pushes the result to the repo and finally merges master into `transifex`. 
At least I hope that it will work like this, we'll see…

The downside of this approach is that every new add-on will need to be configured on Transifex manually by an admin as TX's regular expressions don't seem to work with our file structure. To add an add-on, go to https://www.transifex.com/widelands/widelands-addons/settings/integrations/ → ··· → Edit Settings → Select Files and add an entry for the new resource. The resources should also be renamed manually.
When we have a real add-ons server one day we must switch to a CLI script like for the main game repo.

**Comment by Noordfrees** [comment]
I've suspended Transifex's integration feature and am now writing a script to let the GitHub action handle the TX integration instead. This approach is more scalable and maintainer-friendly and has the advantage that partially complete translations will be pulled as well.
