### ISSUE TITLE
Problem with stonecutter

### ISSUE THREAD

**Issue by Nick222** [widelands/wl_addons_server#123]
The stonecutter tries to get out of the hut, reaches the nearest flag - and comes back.
And so on ad infinitum...

**Comment by frankystone** [comment]
Hi Nick222,

is this related to a widelands add-on? If not this should go into the [widelands issue tracker](https://github.com/widelands/widelands/issues).

Please describe in more detail what is happening, which version do you play, the OS, which add-ons are activated and so on. Also add a save game :-)

**Comment by Nick222** [comment]
Xubuntu 21.10
Widelands 1.0
European Tribe 2.2.6+88
[replays.zip](https://github.com/widelands/wl_addons_server/files/7935330/replays.zip)

**Comment by frankystone** [comment]
Thanks for the information.

I have informed MarcMcWire, who made this add-on :-)

**Comment by Noordfrees** [comment]
@MarkMcWire friendly ping :) what is the status here?

**Comment by MarkMcWire** [comment]
There is some bug I've created. The advanced_stonecutter can become a advanced_stonemason, also the normal_stonemason can become a advanced_stonemason. This caused a crash in my AI-Test-games, because game can't handle this.

But I don't think this is related to the problem from above.  Nevertheless, I made several updates, mainly because the German translations were wrong because _push_textdomain("europeans_tribe.wad", true)_ was missing and instead _push_textdomain("tribe", true)_ was in some entries.

Maybe the other bug is gone, too. Newest Version is 2.3.1, i've uploaded moments ago.

**Comment by hessenfarmer** [comment]
@Nick222 did you test with latest addon version? can this be closed?

**Comment by Nick222** [comment]
> @Nick222 did you test with latest addon version? can this be closed?

Addon version 2.4.5+93 - NO

**Comment by Nick222** [comment]
There is a lot of rocks in stonecutter area - but  the worker leave the house briefly and then come back in again.

**Comment by MarkMcWire** [comment]
> There is a lot of rocks in stonecutter area - but the worker leave the house briefly and then come back in again.

I've increased search radius for rock. Did it have any effect on your problem?

**Comment by Nick222** [comment]
The problem is that at the end of the construction of the quarry, the worker begins to extract stone, however, after extracting 5 units of stone, he stops doing this and enters the cycle I described above.

**Comment by hessenfarmer** [comment]
the problem is the mining program of the worker. after a findspace command a walk=object makes no sense but it should have been a walk=coords see fisher programs for example

**Comment by Nick222** [comment]
Now (version addon 2.4.7+95) mining has begun to go on continuously, but for some reason, a quarry worker extracts quartz and diamonds from the first level, and not, as before, from the second or third...

**Comment by MarkMcWire** [comment]
> Now (version addon 2.4.7+95) mining has begun to go on continuously, but for some reason, a quarry worker extracts quartz and diamonds from the first level, and not, as before, from the second or third...

Yes, thats no bug but a faeature. Quartz and diamond are necessary for recruiting soldiers and the AI stalls some times, so I expanded the extraction of quartz and diamond to all stonecutters, but with different speeds and frequencies.

**Comment by Nick222** [comment]
OK :)

But why normal quarry can only destroy - not to deconstruct ?
