### ISSUE TITLE
europeans addon 3.0.0 123 special worker 'carrier' not defined

### ISSUE THREAD

**Issue by HeHaWN** [widelands/wl_addons_server#139]
widelands with activated addon europeans_tribes.wad do not start on ubuntu 20.04.01. 
shown error: special worker 'carrier' not define
![Bildschirmfoto von 2022-06-18 07-11-06](https://user-images.githubusercontent.com/48024789/174423805-9b2d1095-5753-41fd-aba7-737d9fbef1e1.png)
d

**Comment by MarkMcWire** [comment]
Solved in 3.0.1.
