### ISSUE TITLE
Addon europeans 3.2-1+157

### ISSUE THREAD

**Issue by HeHaWN** [widelands/wl_addons_server#143]
Unplayable since 3 updates

The problem is the woodcoin, which are not generated with all buildings either in the single game or in the multi-user game.
thus neither soil improvers nor training camps are supplied.

**Comment by hessenfarmer** [comment]
@HeHaWN can we consider this closed as the addon is now at version 3.2.9

**Comment by hessenfarmer** [comment]
no reaction on this so I am closing it
