### ISSUE TITLE
[European tribe] missing sticky note animation; making game crash.

### ISSUE THREAD

**Issue by dreirund** [widelands/wl_addons_server#148]
The European tribe misses the "sticky note" animation, which makes the game crash when trying to add a sticky note, or, in recent versions where checks for missing animations are added, makes the game refuse to start.

See https://github.com/widelands/widelands/issues/5860 and https://github.com/widelands/widelands/pull/5862.

**Comment by dreirund** [comment]
Fixed according to [&nearr;&hairsp;this Widelands forum post](https://www.widelands.org/forum/topic/5082/?page=5#post-40341).

**Comment by Noordfrees** [comment]
Bunnybot is misbehaving, trying to fix it
