### ISSUE TITLE
foreign planet addon shows weird graphics in editor

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/wl_addons_server#2]
![grafik](https://user-images.githubusercontent.com/43039887/100386925-00c99200-3027-11eb-893a-2063abedc658.png)

using the terrains of the foreign planet addon result in this graphics

**Comment by Noordfrees** [comment]
Does the issue go away after restarting Widelands or is it still like this?

**Comment by hessenfarmer** [comment]
it is cleard after restart and shows the expected terrains. thanks

**Comment by Noordfrees** [comment]
This bug happens because Widelands expects terrains to be all in the same texture atlas which is created on startup. I'll add a message informing about the need to restart after a user installs a world-type add-on.
