### ISSUE TITLE
Problems with themes

### ISSUE THREAD

**Issue by frankystone** [widelands/wl_addons_server#23]
I have started to make a new theme as an add-on. The first thing i did was to copy the theme from matthiakl to a new folder called `minimalistic_theme.wad` below `./widelands/addons/`. Then i have created new window borders and saved them in `fsmenu/windows/` and `wui/windows/` with the correct name ([top, right, left, bottom].png). But the new 
borders  are not shown when starting widelands + activate this addon + restart widelands. All windows, also inside a game, use the original window borders.

mathiakl's theme doesn't work either correct: Most of the defined images are __not__ used if this addon is activated.

[minimalistic_theme.zip](https://github.com/widelands/wl_addons_server/files/6045956/minimalistic_theme.zip)

widelands version: [3cb6de2@master] (Debug)

**Comment by Noordfrees** [comment]
I'm not sure if I understand the problem correctly. It seems to work fine for me:
Can you provide screenshots of the problem, and state which images exactly you would expect to see and what images are used instead?
![grafik](https://user-images.githubusercontent.com/48293446/109226724-847a5280-77bf-11eb-86e7-e627c674751c.png)

**Comment by frankystone** [comment]
Hm, i can't get it work. Only activated mathiakl's theme:

![shot0001](https://user-images.githubusercontent.com/6730556/109267365-bb755600-7809-11eb-8dfe-5fc73a751e32.jpg)

The background image is still the original one.

**Comment by frankystone** [comment]
Started also with a clean `config` file, but no luck. The config has a key `theme` which points to "templates/default" :

~~~~
theme="templates/default"
addons="auto_soldiers_cs.wad:false,free_heroes.wad:false,free_heroes_new.wad:false,legacy_ui.wad:true,minimalistic_theme.wad:false"
~~~~

**Comment by Noordfrees** [comment]
You also need to select the Theme in the options menu (dropdown "Nutzeroberflächenthema")

**Comment by frankystone** [comment]
Ahhhh, i knew i made a stupid failure.... Thanks.

There are too many options in the meantime imho.

And it looks like some values are hardcoded, e.g. the border width.

**Comment by Noordfrees** [comment]
Yes, there's still a lot of UI-related stuff that should be moved to Lua in the long run.

The Interface and Window tabs of the options menu were merged recently because the tab row got too wide, so it seems rather cluttered now. Suggestions how to unclutter it without adding more tabs welcome…
