### ISSUE TITLE
First Heroes Win string issues

### ISSUE THREAD

**Issue by Noordfrees** [widelands/wl_addons_server#35]
@frankystone 3 transifex string issues were found in the First Heroes Win resource:

- `The player who has at least %1% fully trained soldiers in his warehouses wins the game.`
    -  The statement is confusing. Why is "at least" there? Could the winner have also more heroes? And why isn't "as first one" there? Everyone who will have more than the number of heroes wins? I really don't understand its confusing. The sentence says something, I don't expect. 
- `%1% heroes`
    -  When compound messages are used it is good to leave a developer comment on how the sentence is build. It is not clear what case should I use here 1st or 4th, it makes a difference.
https://en.wikipedia.org/wiki/Czech_declension 
- `%1%: %2%`
    -  Developer note needed.

**Comment by frankystone** [comment]
> @frankystone 3 transifex string issues were found in the First Heroes Win resource:
> 
> * `The player who has at least %1% fully trained soldiers in his warehouses wins the game.`
>   
>   * The statement is confusing. Why is "at least" there? Could the winner have also more heroes? And why isn't "as first one" there? Everyone who will have more than the number of heroes wins? I really don't understand its confusing. The sentence says something, I don't expect.

The count for heroes is done every 5s. If a player has more training camps it might be possible that this player has more than 4 heroes. Unlikely, but could happen, imho.
But yes, there could also be more than one player having 4 heroes.

`The players who have at least %1% fully trained soldiers in his warehouses wins the game.` ?

> * `%1% heroes`
>   
>   * When compound messages are used it is good to leave a developer comment on how the sentence is build. It is not clear what case should I use here 1st or 4th, it makes a difference.
>     https://en.wikipedia.org/wiki/Czech_declension
> * `%1%: %2%`
>   
>   * Developer note needed.

Both refer to [this line](https://github.com/widelands/wl_addons_server/blob/master/addons/first_heroes_win.wad/init.lua#L118)?

Don't know what i should add here. Something like:

~~~~
-- TRANSLATORS: Just use numbers here. It evaluates to: "Player 2: 3 heroes"
~~~~
?

**Comment by Noordfrees** [comment]
Added the explanation to the Transifex comments.

I guess the latter could be changed like this:
```
-- TRANSLATORS: This is an item in a list in the form "Player Name: 3 heroes"
scores = scores .. ngettext("%1%: %2% hero", "%1%: %2% heroes", plr_data[plr.number].nr_heroes):bformat(plr.name, plr_data[plr.number].nr_heroes) .. "\n"
```

**Comment by frankystone** [comment]
Thanks!

**Comment by Noordfrees** [comment]
Another one:
- `Hero Statistic:`
    - typo: Statistics
