### ISSUE TITLE
New europeans tribe as addon.

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/wl_addons_server#42]
I am now completely done with the conversion, the tribe seems to be running. How can I get this to you? As a zip file?

**Comment by Noordfrees** [comment]
Yes best upload the folder here as a zip and I'll take care of the server-side maintenance

**Comment by MarkMcWire** [comment]
https://drive.google.com/file/d/10stvMSlXayCjzwbBb0wn9PccEkIC8y4V/view?usp=sharing
