### ISSUE TITLE
Update Europeans tribe to Version 1.1.1, fixed some problems (see forum)

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/wl_addons_server#44]
Change buildcosts of normal and advanced buildings and fixed some string issues, hessenfarmer pointed out in forum.

https://drive.google.com/file/d/10stvMSlXayCjzwbBb0wn9PccEkIC8y4V/view?usp=sharing

**Comment by Noordfrees** [comment]
Uploaded in 9f1abd1685a7fa0182cbaf6d11e0e024b783eee8. 

Next time can you please try updating the files in your [repo fork](https://github.com/MarkMcWire/wl_addons_server) instead, and making a pull request according to the procedure described in the [README](https://github.com/widelands/wl_addons_server/blob/master/README.md#prerequisites)? 
But if this doesn't work for you (it's not designed for user-friendliness 😉) submitting the upgrades via the links like before is also fine though.
