### ISSUE TITLE
Investigating AI Bug with Europeans tribe

### ISSUE THREAD

**Issue by MarkMcWire** [widelands/wl_addons_server#68]
Can please someone investigate, why the AI only build 1 mine per type, 3 mines in total, for the europeans tribe and so the upgrade of battlearena are blocked. It is still a mysterious bug that prevents a useful gameplay as AI, since AI never can train their soldiers to maximal level without this building upgrade.

**Comment by Noordfrees** [comment]
Difference to https://github.com/widelands/widelands/issues/4669?

**Comment by MarkMcWire** [comment]
oh, sorry, I forgot the other one.
