### ISSUE TITLE
Transifex string issues in `europeans_tribe.wad`

### ISSUE THREAD

**Issue by Noordfrees** [widelands/wl_addons_server#70]
String issues in the Europeans Tribe add-on found by translators. 
@MarkMcWire 

---

String:
> Blackroots are a special kind of root. Sheep farms need to be provided with corn.
> ` addons/europeans_tribe.wad/tribes/europeans_tribe/units.lua:313 `

Comment:
>  This helptext doesn't make much sense. It looks like the second sentence is not related to blackroot.

**Comment by MarkMcWire** [comment]
Changed.

**Comment by Noordfrees** [comment]
Another one found:

> Needöes are used by weaver.
>  `addons/europeans_tribe.wad/tribes/europeans_tribe/units.lua:646 `

> Needöes should be probably needles.
